name: Build Examples

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Espressif IoT Development Framework (ESP-IDF)
      uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        esp_idf_version: release-v5.1
        target: esp32
        path: '.'
        command: idf.py build
    - name: Compile all tests
      run: bash examples/run.sh .